[package]
authors = ["deciduously <ben@deciduously.com>"]
edition = "2018"
name = "deciduously-com-publish"
version = "0.1.0"
[dependencies]
lazy_static = "1.4"
pest = "2.1"
pest_derive = "2.1"

[dev-dependencies]
pretty_assertions = "0.6"
