/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Address,
  CvData,
  CvImageLink,
  Employment,
  Header,
  Intro,
  MonthYear,
  Project,
  SchoolEntry,
} from './cvdata';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';
import {
  BlagPost,
} from './posts';

export namespace Components {
  interface AppBlag {}
  interface AppCv {
    /**
    * Resume data object
    */
    'data': CvData;
  }
  interface AppHome {}
  interface AppPost {
    'blagPost': BlagPost;
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppRoot {}
  interface CvAddress {
    /**
    * Address object
    */
    'address': Address;
  }
  interface CvEducation {
    /**
    * Schools list
    */
    'schools': SchoolEntry[];
  }
  interface CvEmployment {
    /**
    * Employment array
    */
    'employment': Employment[];
  }
  interface CvHeader {
    /**
    * Header data
    */
    'header': Header;
  }
  interface CvIntro {
    /**
    * Intro object
    */
    'intro': Intro;
  }
  interface CvLink {
    /**
    * Link object with image URL
    */
    'link': CvImageLink;
  }
  interface CvMonthyear {
    /**
    * Month and Year
    */
    'date': MonthYear;
  }
  interface CvProjects {
    /**
    * Projects list
    */
    'projects': Project[];
  }
  interface CvSection {
    /**
    * Section name in bold
    */
    'name': string;
  }
}

declare global {


  interface HTMLAppBlagElement extends Components.AppBlag, HTMLStencilElement {}
  var HTMLAppBlagElement: {
    prototype: HTMLAppBlagElement;
    new (): HTMLAppBlagElement;
  };

  interface HTMLAppCvElement extends Components.AppCv, HTMLStencilElement {}
  var HTMLAppCvElement: {
    prototype: HTMLAppCvElement;
    new (): HTMLAppCvElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppPostElement extends Components.AppPost, HTMLStencilElement {}
  var HTMLAppPostElement: {
    prototype: HTMLAppPostElement;
    new (): HTMLAppPostElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCvAddressElement extends Components.CvAddress, HTMLStencilElement {}
  var HTMLCvAddressElement: {
    prototype: HTMLCvAddressElement;
    new (): HTMLCvAddressElement;
  };

  interface HTMLCvEducationElement extends Components.CvEducation, HTMLStencilElement {}
  var HTMLCvEducationElement: {
    prototype: HTMLCvEducationElement;
    new (): HTMLCvEducationElement;
  };

  interface HTMLCvEmploymentElement extends Components.CvEmployment, HTMLStencilElement {}
  var HTMLCvEmploymentElement: {
    prototype: HTMLCvEmploymentElement;
    new (): HTMLCvEmploymentElement;
  };

  interface HTMLCvHeaderElement extends Components.CvHeader, HTMLStencilElement {}
  var HTMLCvHeaderElement: {
    prototype: HTMLCvHeaderElement;
    new (): HTMLCvHeaderElement;
  };

  interface HTMLCvIntroElement extends Components.CvIntro, HTMLStencilElement {}
  var HTMLCvIntroElement: {
    prototype: HTMLCvIntroElement;
    new (): HTMLCvIntroElement;
  };

  interface HTMLCvLinkElement extends Components.CvLink, HTMLStencilElement {}
  var HTMLCvLinkElement: {
    prototype: HTMLCvLinkElement;
    new (): HTMLCvLinkElement;
  };

  interface HTMLCvMonthyearElement extends Components.CvMonthyear, HTMLStencilElement {}
  var HTMLCvMonthyearElement: {
    prototype: HTMLCvMonthyearElement;
    new (): HTMLCvMonthyearElement;
  };

  interface HTMLCvProjectsElement extends Components.CvProjects, HTMLStencilElement {}
  var HTMLCvProjectsElement: {
    prototype: HTMLCvProjectsElement;
    new (): HTMLCvProjectsElement;
  };

  interface HTMLCvSectionElement extends Components.CvSection, HTMLStencilElement {}
  var HTMLCvSectionElement: {
    prototype: HTMLCvSectionElement;
    new (): HTMLCvSectionElement;
  };
  interface HTMLElementTagNameMap {
    'app-blag': HTMLAppBlagElement;
    'app-cv': HTMLAppCvElement;
    'app-home': HTMLAppHomeElement;
    'app-post': HTMLAppPostElement;
    'app-root': HTMLAppRootElement;
    'cv-address': HTMLCvAddressElement;
    'cv-education': HTMLCvEducationElement;
    'cv-employment': HTMLCvEmploymentElement;
    'cv-header': HTMLCvHeaderElement;
    'cv-intro': HTMLCvIntroElement;
    'cv-link': HTMLCvLinkElement;
    'cv-monthyear': HTMLCvMonthyearElement;
    'cv-projects': HTMLCvProjectsElement;
    'cv-section': HTMLCvSectionElement;
  }
}

declare namespace LocalJSX {
  interface AppBlag {}
  interface AppCv {
    /**
    * Resume data object
    */
    'data'?: CvData;
  }
  interface AppHome {}
  interface AppPost {
    'blagPost'?: BlagPost;
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }
  interface AppRoot {}
  interface CvAddress {
    /**
    * Address object
    */
    'address'?: Address;
  }
  interface CvEducation {
    /**
    * Schools list
    */
    'schools'?: SchoolEntry[];
  }
  interface CvEmployment {
    /**
    * Employment array
    */
    'employment'?: Employment[];
  }
  interface CvHeader {
    /**
    * Header data
    */
    'header'?: Header;
  }
  interface CvIntro {
    /**
    * Intro object
    */
    'intro'?: Intro;
  }
  interface CvLink {
    /**
    * Link object with image URL
    */
    'link'?: CvImageLink;
  }
  interface CvMonthyear {
    /**
    * Month and Year
    */
    'date'?: MonthYear;
  }
  interface CvProjects {
    /**
    * Projects list
    */
    'projects'?: Project[];
  }
  interface CvSection {
    /**
    * Section name in bold
    */
    'name'?: string;
  }

  interface IntrinsicElements {
    'app-blag': AppBlag;
    'app-cv': AppCv;
    'app-home': AppHome;
    'app-post': AppPost;
    'app-root': AppRoot;
    'cv-address': CvAddress;
    'cv-education': CvEducation;
    'cv-employment': CvEmployment;
    'cv-header': CvHeader;
    'cv-intro': CvIntro;
    'cv-link': CvLink;
    'cv-monthyear': CvMonthyear;
    'cv-projects': CvProjects;
    'cv-section': CvSection;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-blag': LocalJSX.AppBlag & JSXBase.HTMLAttributes<HTMLAppBlagElement>;
      'app-cv': LocalJSX.AppCv & JSXBase.HTMLAttributes<HTMLAppCvElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-post': LocalJSX.AppPost & JSXBase.HTMLAttributes<HTMLAppPostElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'cv-address': LocalJSX.CvAddress & JSXBase.HTMLAttributes<HTMLCvAddressElement>;
      'cv-education': LocalJSX.CvEducation & JSXBase.HTMLAttributes<HTMLCvEducationElement>;
      'cv-employment': LocalJSX.CvEmployment & JSXBase.HTMLAttributes<HTMLCvEmploymentElement>;
      'cv-header': LocalJSX.CvHeader & JSXBase.HTMLAttributes<HTMLCvHeaderElement>;
      'cv-intro': LocalJSX.CvIntro & JSXBase.HTMLAttributes<HTMLCvIntroElement>;
      'cv-link': LocalJSX.CvLink & JSXBase.HTMLAttributes<HTMLCvLinkElement>;
      'cv-monthyear': LocalJSX.CvMonthyear & JSXBase.HTMLAttributes<HTMLCvMonthyearElement>;
      'cv-projects': LocalJSX.CvProjects & JSXBase.HTMLAttributes<HTMLCvProjectsElement>;
      'cv-section': LocalJSX.CvSection & JSXBase.HTMLAttributes<HTMLCvSectionElement>;
    }
  }
}


